grafana:
  enabled: true
  adminPassword: somecrazypass
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

    hosts:
      - grafana.foreachtoil.com
    tls:
     - secretName: grafana-general-tls
       hosts:
       - grafana.foreachtoil.com
