---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-prometheus'
    spec:
      destination:
        server: '{{server}}'
        namespace: prometheus
      project: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: "51.10.0"
          valuesFile:
            - $argocd/values/prometheus.yaml
          helm:
            releaseName: demo
        - repoURL: https://github.com/foreachtoil/argocd.git
          targetRevision: main
          ref: argocd
