---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-argo-rollouts'
    spec:
      destination:
        server: '{{server}}'
        namespace: argo-rollouts
      project: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-rollouts
          targetRevision: "2.32.0"
          helm:
            releaseName: argo-rollouts
            values: |
              dashboard:
                enabled: true
