---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager'
    spec:
      destination:
        server: '{{server}}'
        namespace: cert-manager
      project: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: "v1.13.1"
          helm:
            releaseName: cert-manager
            values: |
              installCRDs: true
        - repoURL: https://github.com/foreachtoil/argocd
          path: cert-manager
          targetRevision: main