---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: production
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-production'
    spec:
#      ignoreDifferences:
#        - group: apps
#          kind: Rollouts
#          jsonPointers:
#            - /spec/strategy/canary/trafficRouting
#        - group:
      destination:
        server: '{{server}}'
        namespace: production
      project: default
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: https://github.com/foreachtoil/argocd
          path: production
          targetRevision: main